### ISSUE TITLE
Parallel processing for multiple locations

### ISSUE THREAD

**Issue by vmandela99** [adamhsparks/nasapower-example#1]
Hi Adams,

Nice Example there, I wonder if you have a snippet of code to optimize this code when you have a bit more locations. Is it possible to do this in multisession using the purrr package or the future package. A small example would help big time. 

Thanks again for your great work and contribution.

**Comment by adamhsparks** [comment]
@vmandela99, something like the examples here, perhaps? http://adamhsparks.github.io/epicrop/articles/multiples.html

**Comment by vmandela99** [comment]
Hi Adam,

This is actually great. Thanks a bunch. Such a detailed article indeed. Im
gonna ship it!. :)
